# Generated by Django 4.1.4 on 2023-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilmModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Please, enter film name", max_length=256
                    ),
                ),
                ("poster", models.ImageField(upload_to="posters/")),
                ("video", models.FileField(upload_to="videos/")),
                ("rating", models.FloatField(default=0)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.IntegerField(default=0)),
                ("about", models.TextField(blank=True, null=True)),
            ],
            options={"verbose_name": "Film",},
        ),
    ]
