# Generated by Django 4.1.4 on 2023-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0003_likemodel_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmmodel",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
