# Generated by Django 4.1.4 on 2023-05-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0004_filmmodel_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "films",
                    models.ManyToManyField(
                        related_name="categories", to="film.filmmodel"
                    ),
                ),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
    ]
