# Generated by Django 4.1.4 on 2023-05-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Please enter your name", max_length=150
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Please enter your surname", max_length=150
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                ("message", models.TextField()),
            ],
            options={"verbose_name": "Contact",},
        ),
    ]
